### ISSUE TITLE
bject_detector.Dataset.from_pascal_voc_folder ignores negative/background images

### ISSUE THREAD

**Issue by willemnator** [google-ai-edge/mediapipe#4423]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux

### Python Version

3.10

### MediaPipe Model Maker version

0.2.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detection

### Describe the actual behavior

```shell
object_detector.Dataset.from_pascal_voc_folder() 
```
Is not including negative/background images. These are images that have no object / bounding box in the XML. These are crucial to include for good object detection training. This differs with how tflite-model-maker works, where these images are included.

### Describe the expected behaviour

Similar as with how it works in tflite-model-maker, images with no bounding box are included in the training, for example when the annotation file is as below:

```shell

<annotation verified="yes">
	<folder>unprocessed_control</folder>
	<filename>0b44ce15-aed7-4330-9988-2bbd17e69a7a.jpg</filename>
	<path>0b44ce15-aed7-4330-9988-2bbd17e69a7a.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>640</width>
		<height>480</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
</annotation>
```

### Standalone code/steps you may have used to try to get what you need

Use above XML with tflite-model-maker and see it being part of the training data, while with media pipe model maker only images with bounding boxes are included.

**Comment by kuaashish** [comment]
@willemnator,
Would you please let us know the complete steps you have followed to reproduce the issue from our end?

**Comment by willemnator** [comment]
i followed the [object_detector customize from google tutorial ](https://developers.google.com/mediapipe/solutions/vision/object_detector/customize) with the addition of loading training data using from_pascal_voc_folder.

**Comment by kuaashish** [comment]
@willemnator,

Sorry for the delayed response, Are you still for the resolution on this issue or it has been resolved from your end? Thank you

**Comment by willemnator** [comment]
@kuaashish 
This should be prio'd because at its current state you can't train a good Object detection model. To train a good model you have to be able to include background images. It is not solved.

**Comment by kuaashish** [comment]
@willemnator,

Could you please share detailed explanation which you have observed the difficulty to train a good object detection model? And We will let the team knows about the issue. Thank you!

**Comment by willemnator** [comment]
In object detection training it doesn't allow for including negative/background images. With tflite-model-maker it does. That is it. More details are in the main post.

**Comment by kuaashish** [comment]
Hello @ahmadyan, @lzhang57,

Could you please look into this issue? Thank you!!

**Comment by saraswathykrk** [comment]
Hi,

I followed the object detection tutorial, but I am getting the below error when I run the code for train dataset. Can you please let me know what the issue is - because the data directory is not empty and I am storing the image files under images folder and xml files under annotations folder.

Error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-27-e76a53d8b7f6>](https://localhost:8080/#) in <cell line: 1>()
----> 1 validation_data = object_detector.Dataset.from_pascal_voc_folder(validation_dataset_path, cache_dir="/content/files/cache/validation")
      2 print("train_data size: ", train_data.size)
      3 print("validation_data size: ", validation_data.size)

4 frames
[/usr/local/lib/python3.10/dist-packages/mediapipe_model_maker/python/core/data/cache_files.py](https://localhost:8080/#) in __post_init__(self)
     51       raise ValueError('cache_prefix_filename cannot be empty.')
     52     if self.num_shards <= 0:
---> 53       raise ValueError(
     54           f'num_shards must be greater than 0, got {self.num_shards}'
     55       )

ValueError: num_shards must be greater than 0, got 0


File structure:

/content/files/annotated_products/annotated_products/train
total 8
drwxr-xr-x 2 root root 4096 Aug 14 05:19 images
drwxr-xr-x 2 root root 4096 Aug 14 05:19 annotations
/content/files/annotated_products/annotated_products/train/images
qr10.jpg  qr19.jpg  qr26.jpg  qr34.jpg	qr42.jpg  qr4.jpg   qr57.jpg
qr12.jpg  qr1.jpg   qr28.jpg  qr35.jpg	qr43.jpg  qr50.jpg  qr58.jpg
qr13.jpg  qr20.jpg  qr29.jpg  qr36.jpg	qr44.jpg  qr51.jpg  qr59.jpg
qr14.jpg  qr21.jpg  qr2.jpg   qr37.jpg	qr46.jpg  qr52.jpg  qr5.jpg
qr15.jpg  qr23.jpg  qr30.jpg  qr38.jpg	qr47.jpg  qr53.jpg  qr6.jpg
qr16.jpg  qr24.jpg  qr31.jpg  qr39.jpg	qr48.jpg  qr55.jpg  qr8.jpg
qr17.jpg  qr25.jpg  qr33.jpg  qr41.jpg	qr49.jpg  qr56.jpg  qr9.jpg
/content/files/annotated_products/annotated_products/train/annotations
qr10.xml  qr19.xml  qr26.xml  qr34.xml	qr42.xml  qr4.xml   qr57.xml
qr12.xml  qr1.xml   qr28.xml  qr35.xml	qr43.xml  qr50.xml  qr58.xml
qr13.xml  qr20.xml  qr29.xml  qr36.xml	qr44.xml  qr51.xml  qr59.xml
qr14.xml  qr21.xml  qr2.xml   qr37.xml	qr46.xml  qr52.xml  qr5.xml
qr15.xml  qr23.xml  qr30.xml  qr38.xml	qr47.xml  qr53.xml  qr6.xml
qr16.xml  qr24.xml  qr31.xml  qr39.xml	qr48.xml  qr55.xml  qr8.xml
qr17.xml  qr25.xml  qr33.xml  qr41.xml	qr49.xml  qr56.xml  qr9.xml

![image](https://github.com/google/mediapipe/assets/44539281/8d135e26-347d-4e10-a7ef-ccd6aede5f81)

![image](https://github.com/google/mediapipe/assets/44539281/2a6d42e0-cb23-4c8b-b84b-cc801b6116e0)

Regards

**Comment by willemnator** [comment]
Yeh at least when using from_pascal_voc_folder() - and it's still not fixed. I think google has moved all their resources to language models.

**Comment by mdespinoza** [comment]
Yeah there is still no fix for this - supper annoying.

**Comment by Sombraa711** [comment]
This may solve the problem if you are urgent:

In dataset_util.py

comment this:
https://github.com/google-ai-edge/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/dataset_util.py#L443-L445

or this if you are using coco format:
https://github.com/google-ai-edge/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/dataset_util.py#L389-L391


modify _bbox_data_to_feature_dict to:
```

def _bbox_data_to_feature_dict(data):
  """Converts a dictionary of bbox annotations to a feature dictionary.

  Args:
    data: Dict with keys 'xmin', 'xmax', 'ymin', 'ymax', 'category_id'

  Returns:
    Feature dictionary
  """
  if not data['xmin']:
    bbox_feature_dict = {
        'image/object/bbox/xmin': tfrecord_lib.convert_to_feature([0.0]),
        'image/object/bbox/xmax': tfrecord_lib.convert_to_feature([0.0]),
        'image/object/bbox/ymin': tfrecord_lib.convert_to_feature([0.0]),
        'image/object/bbox/ymax': tfrecord_lib.convert_to_feature([0.0]),
        'image/object/class/label': tfrecord_lib.convert_to_feature([0]),
    }
  else:
    bbox_feature_dict = {
        'image/object/bbox/xmin': tfrecord_lib.convert_to_feature(data['xmin']),
        'image/object/bbox/xmax': tfrecord_lib.convert_to_feature(data['xmax']),
        'image/object/bbox/ymin': tfrecord_lib.convert_to_feature(data['ymin']),
        'image/object/bbox/ymax': tfrecord_lib.convert_to_feature(data['ymax']),
        'image/object/class/label': tfrecord_lib.convert_to_feature(
            data['category_id']
        ),
    }
  return bbox_feature_dict
```

It should work.

**Comment by HarishPermal** [comment]
hi @willemnator,

Sorry for the delayed response, This issue still remains reproducible with `mediapipe-model-maker==0.2.1.4` so I tried a workaround that retains these images using correctly typed empty TFRecord bounding-box features, rather than adding a fake background bounding box. So the reproducible docker environment and patch are available [here](https://github.com/HarishPermal/4423-mediapipe.git) and MediaPipe Model Maker is now officially [deprecated](https://developers.google.com/edge/mediapipe/solutions/model_maker) and no longer actively maintained so this workaround may still help existing users.

Thanks.
