### ISSUE TITLE
INTERNAL: Service "kGpuService", required by node mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph...

### ISSUE THREAD

**Issue by V-m1r** [google-ai-edge/mediapipe#5609]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

iOS 16.4 and iOS 16.6

### MediaPipe Tasks SDK version

0.10.15

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Landmarker

### Programming Language and version (e.g. C++, Python, Java)

JavaScript

### Describe the actual behavior

tasks-vision -> detectForVideo function doesn't work for iOS 16.4 and 16.6 even with CPU delegate

### Describe the expected behaviour

Should work because Pose (Legacy solution) works on iOS 16.4 and 16.6

### Standalone code/steps you may have used to try to get what you need

```shell
// Mediapipe warmup

this.poseLandmarker = await PoseLandmarker.createFromOptions(vision, {
          baseOptions: {
            modelAssetPath: modelURL, // tried with full and lite models 
            delegate: "CPU"

          },
          minPoseDetectionConfidence: 0.6,
          minPosePresenceConfidence: 0.6,
          minTrackingConfidence: 0.6,
          runningMode: "VIDEO",
          numPoses: 1,
        });
        const canvas = document.createElement('canvas');
        canvas.width = 1;
        canvas.height = 1;
    
        const ctx = canvas.getContext('2d');
        if (ctx) {
          // Clear the canvas before drawing
          ctx.clearRect(0, 0, canvas.width, canvas.height);
          
          // Draw a single pixel
          ctx.fillRect(0, 0, 1, 1);
      
          this.poseLandmarker.detectForVideo(canvas, performance.now(),  (result) => {
            console.log("[event] PoseLandmarker initialized successfully");
            this.isInitialized = true;
            // Clear the canvas after we're done
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            
            return this.poseLandmarker;
          });
        }
```
```


### Other info / Complete Logs

```shell
error
06:00:27.000
Error: INTERNAL: Service "kGpuService", required by node mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_...

....
TypeError: undefined is not an object (evaluating 'GLctx.activeTexture')
```

**Comment by V-m1r** [comment]
Hello Everyone. Wanted to update: the issue is isolated only to iOS 16.4 and iOS 16.6 versions. I tried iOS 16.1 and iOS 15, both work. Legacy Pose Model works on all iOS versions I tested though, we recently migrated to a newer model and are experiencing these issues. I read apple has made some bugs with webql in those updates where webQL 2.0 doesn't work, but what's interesting is that legacy model works. 

Sharing more logs:
```
E0904 03:25:34.992000 1895072 gl_graph_runner_internal.cc:260] StartGraph failed: INTERNAL: Service "kGpuService", required by node mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: emscripten_webgl_create_context() returned error 0; StartRun failed
=== Source Location Trace: ===
third_party/mediapipe/framework/calculator_graph.cc:694
third_party/mediapipe/framework/calculator_graph.cc:725
third_party/mediapipe/framework/calculator_graph.cc:594
research/drishti/app/pursuit/wasm/graph_utils.cc:107

```

```
I0904 03:25:34.983000 1895072 gl_context_webgl.cc:91] Couldn't create webGL 2 context.
W0904 03:25:34.989000 1895072 gl_context_webgl.cc:116] Creating a context with WebGL 2 failed: UNKNOWN: emscripten_webgl_create_context() returned error 0
=== Source Location Trace: ===
third_party/mediapipe/gpu/gl_context_webgl.cc:92


W0904 03:25:34.990000 1895072 gl_context_webgl.cc:117] Fall back on WebGL 1.
I0904 03:25:34.990000 1895072 gl_context_webgl.cc:91] Couldn't create webGL 1 context.
```

Any help would be really appreciated!

**Comment by kuaashish** [comment]
Hi @V-m1r,

Could you please verify if the issue is still present in the most recent version [0.10.18](https://github.com/google-ai-edge/mediapipe/releases/tag/v0.10.18)?

Thank you!!

**Comment by V-m1r** [comment]
Hello @kuaashish 

I am still experiencing this issue on iOS 16.4 simulator. 
I updated  "@mediapipe/tasks-vision" to "^0.10.18" and pose_landmarker_full, and now on iOS 16.4 facing this issue: `undefined is not an object (evaluating 'GLctx.activeTexture')`
Full stack trace: 
```
TypeError: undefined is not an object (evaluating 'GLctx.activeTexture')
  at _glActiveTexture(/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js:10:137770)
  at ? (/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js:10:187896)
  at _0x345eec(/static/js/main.1f66dbf6.js:171:321969)
  at ? (/static/js/main.1f66dbf6.js:171:378234)
  at _0x2a9218(/static/js/main.1f66dbf6.js:171:321656)
  at ? (/static/js/main.1f66dbf6.js:171:378145)
  at _0x160ee8(/static/js/main.1f66dbf6.js:171:381830)
  at _0x3b2fd1(/static/js/main.1f66dbf6.js:171:382306)
  at ? (/static/js/main.1f66dbf6.js:171:474298)
  at ? (/static/js/main.1f66dbf6.js:171:481391)
```

Log: 
```
Exception - This event
error
11:33:55.000 AM
TypeError: undefined is not an object (evaluating 'GLctx.activeTexture')
Console
info
11:33:55.021 AM
Graph successfully started running.

{

arguments: [
1 item
],
logger: console
}
Console
info
11:33:55.016 AM
I1127 11:33:55.016000 1905760 gl_context_webgl.cc:91] Couldn't create webGL 1 context.

{

arguments: [
1 item
],
logger: console
}
Console
info
11:33:55.015 AM
I1127 11:33:55.015000 1905760 gl_context_webgl.cc:91] Couldn't create webGL 2 context.

{

arguments: [
1 item
],
logger: console
}
Console
info
11:33:55.015 AM
I1127 11:33:55.015000 1905760 gl_context_webgl.cc:91] Couldn't create webGL 1 context.

{

arguments: [
1 item
],
logger: console
}

```


My current workaround is to catch the error and utilize the legacy model: 
```typescript
      try {
        this.poseLandmarker = await PoseLandmarker.createFromOptions(vision, {
          baseOptions: {
            modelAssetPath: modelURL,
            delegate: webGLSupported ? "GPU" : "CPU",
          },
          minPoseDetectionConfidence: 0.6,
          minPosePresenceConfidence: 0.6,
          minTrackingConfidence: 0.6,
          runningMode: "VIDEO",
          numPoses: 1,
        });
        const canvas = document.createElement("canvas");
        canvas.width = 1;
        canvas.height = 1;

        const ctx = canvas.getContext("2d");
        if (ctx) {
          // Clear the canvas before drawing
          ctx.clearRect(0, 0, canvas.width, canvas.height);

          // Draw a single pixel
          ctx.fillRect(0, 0, 1, 1);

          this.poseLandmarker.detectForVideo(
            canvas,
            performance.now(),
            (result) => {
              // console.log("[event] PoseLandmarker initialized successfully");
              this.isInitialized = true;
              ctx.clearRect(0, 0, canvas.width, canvas.height);
              return this.poseLandmarker;
            }
          );
        }
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);

        return await this.initializeLegacyModel();
      }


  private async initializeLegacyModel(): Promise<Pose | null> {
    try {
      this.poseLandmarker = new Pose({
        locateFile: (file) =>
          `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`,
      });
      this.poseLandmarker.setOptions({
        modelComplexity: 1,
        minDetectionConfidence: 0.6,
        minTrackingConfidence: 0.6,
      });

      return this.poseLandmarker;
    } catch (legacyError) {
      return null;
    }
  }

```

**Comment by kuaashish** [comment]
Hi @V-m1r,

Apologies, but we do not consider simulators as a platform tested by us. Could you please test it on a real device with the same configuration and provide us with an update on the status?

Thank you!!

**Comment by V-m1r** [comment]
Hello @kuaashish
The same issue happens on real device too. We first noticed it when testing on old iphone 11. I believe this could be connected to this issue: https://forums.developer.apple.com/forums/thread/727443#:~:text=The%20WebGL%20problem%20is%20from,has%20the%20webgl%20context%20too.

**Comment by V-m1r** [comment]
Issue resolved with new version 0.10.20

**Comment by bcjohnblue** [comment]
I encountered the same issue: `undefined is not an object (evaluating 'GLctx.activeTexture')`. Unfortunately, upgrading MediaPipe to `v0.10.20` (or the `latest` version) did not resolve it. I finally managed to fix the error by explicitly passing the `canvas` option when initializing the `PoseLandmarker`.

[reference](https://github.com/google-ai-edge/mediapipe/issues/4499#issuecomment-4021746507)
